external_components:
  - source: github://creepystefan/esphomefauxmo
  
esphome:
  name: alexatest
       
  libraries:
        
    - alexaweenymo=https://github.com/creepystefan/esphomefauxmo
    - ESPAsyncWebServer=https://github.com/esphome/ESPAsyncWebServer
    - ESPAsyncUDP

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apixywfpow

ota:
  platform: esphome
  password: !secret otaxywfpow

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet
 
 
captive_portal:
    
myalexa:
